#!/usr/bin/env tsx
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG_DIR = fileURLToPath(new URL('..', import.meta.url));
const ALUS_ROOT = process.env.ALUS_ROOT ?? resolve(PKG_DIR, '../..');

const COMPONENTS_DIR = `${ALUS_ROOT}/packages/alus/src/lib/components`;
const ROUTES_DIR = `${ALUS_ROOT}/src/routes/components`;
const UTILS_ROOT = `${ALUS_ROOT}/packages/alus/src/lib/utils`;
const CATEGORIES = ['form', 'navigation', 'feedback', 'display', 'overlay', 'layout', 'interactive', 'utility'];
const UTIL_MODULES = ['a11y/aria', 'a11y/focus', 'a11y/id', 'a11y/keyboard', 'a11y/index', 'form/state'];
const OUT = `${PKG_DIR}/src/generated/data.ts`;

async function read_file_safe(path: string): Promise<string | null> {
	try { return await readFile(path, 'utf-8'); } catch { return null; }
}

async function read_dir_safe(path: string): Promise<string[]> {
	try { return await readdir(path); } catch { return []; }
}

const components: Array<{ name: string; category: string; slug: string; files: Record<string, string> }> = [];
for (const category of CATEGORIES) {
	const items = await read_dir_safe(`${COMPONENTS_DIR}/${category}`);
	for (const slug of items) {
		const comp_dir = `${COMPONENTS_DIR}/${category}/${slug}`;
		const dir_files = await read_dir_safe(comp_dir);
		const src_files = dir_files.filter(f => f.endsWith('.svelte') || f.endsWith('.ts'));
		if (!src_files.length) continue;
		const name = slug.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
		const files: Record<string, string> = {};
		for (const f of src_files) {
			const content = await read_file_safe(`${comp_dir}/${f}`);
			if (content !== null) files[f] = content;
		}
		components.push({ name, category, slug, files });
	}
}

// Collect extra files: demos, utils, exports index
const extra_files: Record<string, string> = {};

// components/index.ts
const exports_index = await read_file_safe(`${COMPONENTS_DIR}/index.ts`);
if (exports_index) extra_files['components/index.ts'] = exports_index;

// utils
for (const mod of UTIL_MODULES) {
	const content = await read_file_safe(`${UTILS_ROOT}/${mod}.ts`);
	if (content) extra_files[`utils/${mod}.ts`] = content;
}

// demos
const demo_dirs = await read_dir_safe(ROUTES_DIR);
for (const demo_dir of demo_dirs) {
	const page = await read_file_safe(`${ROUTES_DIR}/${demo_dir}/+page.svelte`);
	if (page) extra_files[`demos/${demo_dir}/+page.svelte`] = page;
}

const output = `// Auto-generated by scripts/bundle-data.ts — do not edit manually
// Run \`pnpm bundle:data\` to regenerate
export const BUNDLED_DATA: {
\tcomponents: Array<{
\t\tname: string;
\t\tcategory: string;
\t\tslug: string;
\t\tfiles: Record<string, string>;
\t}>;
\tfiles: Record<string, string>;
\tgenerated_at: string;
} | null = {
\tcomponents: ${JSON.stringify(components, null, '\t')},
\tfiles: ${JSON.stringify(extra_files, null, '\t')},
\tgenerated_at: ${JSON.stringify(new Date().toISOString())},
};
`;

await writeFile(OUT, output, 'utf-8');
console.log(`✓ bundled ${components.length} components, ${Object.keys(extra_files).length} extra files → src/generated/data.ts`);
